### ISSUE TITLE
Trying ServiceNow Inventory with Ansible AWX

### ISSUE THREAD

**Issue by metabsd** [ServiceNowITOM/servicenow-ansible#36]
Project contain that structure.
`/myproject/collections/requirements.yml`
```
collections:
  - name: servicenow.servicenow
```
`/myproject/inventories/servicenow_unix_all_env.yml`
```
plugin: servicenow.servicenow.now
host: ourdomain.service-now.com
username: ourusername
password: ourpassword
fields: [name,host_name,fqdn,ip_address,sys_class_name, install_status, classification,vendor, os, used_for]
keyed_groups:
  - key: sn_classification | lower
    prefix: 'env'
  - key: sn_vendor | lower
    prefix: ''
    separator: ''
  - key: sn_sys_class_name | lower
    prefix: ''
    separator: ''
  - key: sn_install_status | lower
    prefix: 'status'
  - key: os_version | lower
    prefix: ''
    separator: ''
  - key: used_for | lower
    prefix: ''
    separator: ''
  - key: sys_class_name | lower
    prefix: ''
    separator: ''
```

When I synchronize the project inside AWX I see the collection successfully installed

ERROR:
```
    2.818 INFO     Updating inventory 3: ServiceNow Inventory All Env
    2.833 DEBUG    Using base command: python /usr/bin/ansible-inventory -i /tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml --playbook-dir /tmp/awx_15_safsxp44/project/inventories -vvvvv
    2.833 INFO     Reading Ansible inventory source: /tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml
    2.834 INFO     Using VIRTUAL_ENV: /var/lib/awx/venv/ansible
    2.834 INFO     Using PATH: /var/lib/awx/venv/ansible/bin:/var/lib/awx/venv/awx/bin:/usr/pgsql-10/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    2.834 INFO     Using PYTHONPATH: /var/lib/awx/venv/ansible/lib/python3.6/site-packages:
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1142, in handle
    raise exc
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 1032, in handle
    venv_path=venv_path, verbosity=self.verbosity).load()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 208, in load
    return self.command_to_json(base_args + ['--list'])
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/inventory_import.py", line 191, in command_to_json
    self.method, proc.returncode, stdout, stderr))
RuntimeError: ansible-inventory failed (rc=1) with stdout:
stderr:
ansible-inventory 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml as it did not pass its verify_file() method
script declined parsing /tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml as it did not pass its verify_file() method
Skipping due to inventory source not ending in "now.yaml" nor "now.yml"
toml declined parsing /tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse
/tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml with auto
plugin: inventory config
'/tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml' could
not be verified by plugin 'servicenow.servicenow.now'
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/auto.py", line 56, in parse
    raise AnsibleParserError("inventory config '{0}' could not be verified by plugin '{1}'".format(path, plugin_name))
[WARNING]:  * Failed to parse
/tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml with yaml
plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/yaml.py", line 112, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse
/tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml with ini
plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse
/tmp/awx_15_safsxp44/project/inventories/servicenow_unix_all_env.yml as an
inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

Thanks in advance for helping me!

**Comment by metabsd** [comment]
I fix it by making sure that my file finish by `_now.yml`
