### ISSUE TITLE
Issue upload attachment

### ISSUE THREAD

**Issue by ghost** [ServiceNowITOM/servicenow-ansible#56]
When uploading a file to a ticket the response of ServiceNow gives an error in python snow_record module.

The error log received is:
`The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1618468218.7902899-7725-215875449232816/AnsiballZ_snow_record.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1618468218.7902899-7725-215875449232816/AnsiballZ_snow_record.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1618468218.7902899-7725-215875449232816/AnsiballZ_snow_record.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.servicenow.servicenow.plugins.modules.snow_record', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible_collections/servicenow/servicenow/plugins/modules/snow_record.py", line 457, in <module>
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible_collections/servicenow/servicenow/plugins/modules/snow_record.py", line 453, in main
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible_collections/servicenow/servicenow/plugins/module_utils/service_now.py", line 379, in exit
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible/module_utils/basic.py", line 2189, in exit_json
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible/module_utils/basic.py", line 2182, in _return_formatted
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible/module_utils/basic.py", line 420, in remove_values
  File "/tmp/ansible_snow_record_payload_zg0983g5/ansible_snow_record_payload.zip/ansible/module_utils/basic.py", line 397, in _remove_values_conditions
TypeError: Value of unknown type: <class 'pysnow.response.Response'>, <Response [201 - POST]>`

To fix this you need to update "plugins/modules/snow_record.py" on line 431 with:
`module.result['attached_file'] = res.one()`

**Comment by willtome** [comment]
Please raise this issue against https://github.com/ansible-collections/servicenow.itsm

Thank you!
